sopt-makers/sopt-playground-backend

src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChat.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java

SP1 커피챗 고도화에서 추가된 필드를 바탕으로 정보를 수정하는 API를 추가합니다.
- 코드리뷰의 편의를 위해 #494 와 분리하여 PR 생성합니다.
- 커피챗 정보 수정 API 추가
- 생성 API의 request 그대로 활용
related issue: #482

[Feat] 커피챗 정보 수정 API 

---

src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChat.java
src/main/java/org/sopt/makers/internal/member/dto/request/CoffeeChatOpenRequest.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatUpdater.java

커피챗 공개 여부를 변경할 수 있는 API를 추가합니다.
- 커피챗 공개/비공개 여부 토글 API 추가
- request validation 적용
- 200 Ok
- Request Validation
close: #482

[Feat] 커피챗 공개/비공개 설정 API 추가

---

src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/response/CoffeeChatDetailResponse.java
src/main/java/org/sopt/makers/internal/member/mapper/coffeechat/CoffeeChatResponseMapper.java
src/main/java/org/sopt/makers/internal/member/service/MemberRetriever.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java

사용자의 커피챗 상세 정보를 조회하는 API입니다.
- 관련 로직 구현
- 포스트맨 테스트
close: #501

[Feat]: 커피챗 상세조회 API 구현

---

src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatRepositoryCustomImpl.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java

커피챗 검색 Enum title 필드 적용
- 커피챗 검색 Enum title 필드 적용
close: #508

[Refactor]: 커피챗 검색 Enum title 필드 적용

---

src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java

커피챗 검색 Career 매핑 추가
- 커피챗 검색 Career 매핑 추가
close: #510

[Feat]: 커피챗 검색 Career 매핑 추가

---

src/main/java/org/sopt/makers/internal/dto/member/MemberProfileUpdateRequest.java

MemberProfileUpdateRequest의 커피챗 관련 필드 및 유효성 검사 제외
related issue: #498

[Fix] MemberProfileUpdateRequest 커피챗 관련 필드 제외

---

src/main/java/org/sopt/makers/internal/common/Constant.java

Related to: #516
- 작업 1
- 작업 2
- 작업 3
close: #00

[Fix]: 매직넘버 validation 변경

---

src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatRepositoryCustomImpl.java

- 작업 1
- 작업 2
- 작업 3
close: #00

RELEASE 2024/11/03 10:54:30

---

src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/request/CoffeeChatRequest.java

- 작업 1
- 작업 2
- 작업 3
close: #00

fix: coffee chat 글자수 제한 변경

---

src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/request/CoffeeChatRequest.java

- 작업 1
- 작업 2
- 작업 3
close: #00

RELEASE 2024/11/03 11:54:30

---

src/main/java/org/sopt/makers/internal/controller/AuthController.java

apple tester 계정명을 Tester -> User로 변경합니다.
앱 팀의 심사 리젝사유 중 하나로, 급건으로 판단되어 우선 머지하겠습니다!
- 작업 1
- 작업 2
- 작업 3
close: #516

[Chore] apple tester 계정명 변경

---

src/main/java/org/sopt/makers/internal/controller/AuthController.java

- 작업 1
- 작업 2
- 작업 3
close: #00

RELEASE 2024/11/04 02:09:09

---

src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/response/CoffeeChatDetailResponse.java
src/main/java/org/sopt/makers/internal/member/mapper/coffeechat/CoffeeChatResponseMapper.java

커피챗 상세조회시 section 필드 추가
- 커피챗 상세조회시 section 필드 추가
close: #527

[Fix]: 커피챗 상세조회시 section 필드 추가

---

src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
src/main/java/org/sopt/makers/internal/member/controller/dto/response/MemberInfoResponse.java
src/main/java/org/sopt/makers/internal/member/mapper/MemberResponseMapper.java

members/me API response에 데이터 추가
- members/me API response에 데이터 추가
close: #529

[Feat]: members/me API response에 데이터 추가

---

src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
src/main/java/org/sopt/makers/internal/member/controller/dto/response/MemberInfoResponse.java
src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatRepositoryCustomImpl.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatRetriever.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java

최근 진행된 커피챗 중복조회 해결
- 최근 진행된 커피챗 중복조회 해결
close: #531

[Fix]: 최근 진행된 커피챗 중복조회 해결

---

src/main/java/org/sopt/makers/internal/external/gabia/SmsChatSender.java
src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/request/CoffeeChatDetailsRequest.java
src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/response/CoffeeChatDetailResponse.java
src/main/java/org/sopt/makers/internal/member/controller/dto/response/MemberInfoResponse.java
src/main/java/org/sopt/makers/internal/member/mapper/MemberResponseMapper.java
src/main/java/org/sopt/makers/internal/member/mapper/coffeechat/CoffeeChatResponseMapper.java
src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatRepositoryCustomImpl.java
src/main/java/org/sopt/makers/internal/member/service/MemberRetriever.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatRetriever.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java

- 작업 1
- 작업 2
- 작업 3
close: #00

RELEASE 2024/11/06 21:48:00

---

src/main/java/org/sopt/makers/internal/member/domain/coffeechat/Career.java

커피챗 커리어 필드 추가
STARTUP("창업 중") 필드를 Career.java Enum class에 추가했습니다.
- 커피챗 커리어 필드 추가
close: #541

[Feat]: 커피챗 커리어 필드 추가

---

.gitignore
src/main/java/org/sopt/makers/internal/community/repository/AnonymousProfileImageRepository.java
src/main/java/org/sopt/makers/internal/community/service/AnonymousProfileImageService.java
src/main/java/org/sopt/makers/internal/dto/member/MemberProfileSpecificResponse.java
src/main/java/org/sopt/makers/internal/mapper/MemberMapper.java
src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
src/main/java/org/sopt/makers/internal/member/controller/dto/response/MemberPropertiesResponse.java
src/main/java/org/sopt/makers/internal/member/domain/coffeechat/Career.java
src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChatStatus.java
src/main/java/org/sopt/makers/internal/member/mapper/MemberResponseMapper.java
src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatHistoryRepository.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatRetriever.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/dto/MemberCoffeeChatPropertyDto.java
src/main/java/org/sopt/makers/internal/member/util/MemberUtil.java
src/main/java/org/sopt/makers/internal/service/MemberService.java

- 작업 1
- 작업 2
- 작업 3
close: #00

RELEASE 2024/11/09 20:56:00

---

src/main/java/org/sopt/makers/internal/domain/Member.java
src/main/java/org/sopt/makers/internal/repository/MemberRepository.java

* [Fix]: users테이블에 사용하지 않는 컬럼 삭제
Related to: #545
* [Fix]: 불필요한 어노테이션 삭제
Related to: #545
- 작업 1
- 작업 2
- 작업 3
close: #00

RELEASE 2024/11/10 20:30:00

---

src/main/java/org/sopt/makers/internal/community/repository/CommunityPostRepositoryCustom.java
src/main/java/org/sopt/makers/internal/community/repository/CommunityPostRepositoryCustomImpl.java
src/main/java/org/sopt/makers/internal/community/service/CommunityPostService.java
src/main/java/org/sopt/makers/internal/controller/InternalOpenApiController.java
src/main/java/org/sopt/makers/internal/dto/community/InternalCommunityPost.java
src/main/java/org/sopt/makers/internal/dto/community/PostCategoryDao.java
src/main/java/org/sopt/makers/internal/dto/internal/InternalMemberProjectResponse.java
src/main/java/org/sopt/makers/internal/mapper/CommunityResponseMapper.java
src/main/java/org/sopt/makers/internal/mapper/ProjectResponseMapper.java
src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/response/InternalCoffeeChatMemberResponse.java
src/main/java/org/sopt/makers/internal/member/mapper/coffeechat/CoffeeChatResponseMapper.java
src/main/java/org/sopt/makers/internal/member/repository/coffeechat/dto/InternalCoffeeChatMemberDto.java
src/main/java/org/sopt/makers/internal/member/service/MemberRetriever.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
src/main/java/org/sopt/makers/internal/repository/MemberProfileQueryRepository.java
src/main/java/org/sopt/makers/internal/repository/ProjectQueryRepository.java
src/main/java/org/sopt/makers/internal/repository/community/CommunityPostRepository.java
src/main/java/org/sopt/makers/internal/repository/community/CommunityQueryRepository.java
src/main/java/org/sopt/makers/internal/service/MemberService.java
src/main/java/org/sopt/makers/internal/service/ProjectService.java

- 작업 1
- 작업 2
- 작업 3
close: #00

RELEASE 2024/11/13 00:42:00

---

src/main/java/org/sopt/makers/internal/dto/community/InternalCommunityPost.java
src/main/java/org/sopt/makers/internal/mapper/CommunityResponseMapper.java

최근 커뮤니티 게시글 조회 필드 추가
content 필드 추가됐습니다.
- 최근 커뮤니티 게시글 조회 필드 추가
close: #551

[Feat]: 최근 커뮤니티 게시글 조회 필드 추가

---

src/main/java/org/sopt/makers/internal/dto/community/InternalCommunityPost.java
src/main/java/org/sopt/makers/internal/mapper/CommunityResponseMapper.java

- 작업 1
- 작업 2
- 작업 3
close: #00

RELEASE 2024/11/16 16:09:00

---

scripts/deploy.sh

- 작업 1
- 작업 2
- 작업 3
close: #00

fix: deploy path 변경

---

src/main/java/org/sopt/makers/internal/common/Constant.java

현재 기수를 나타내는 상수값을 수정했습니다.
- 상수값 수정
close: #591

[Chore]: 현재 기수 36기로 업데이트

---

.gitignore
build.gradle
src/main/java/org/sopt/makers/internal/common/GoogleSheetsService.java
src/main/java/org/sopt/makers/internal/resolution/service/UserResolutionService.java
src/main/java/org/sopt/makers/internal/resolution/service/UserResolutionServiceUtil.java
src/test/resources/application.yml

- 구글 스프레드 시트 의존성 추가
- 타임캡솝 작성 시 구글 스프레드 시트 연동
- 연동 실패 시 로그에 에러 작성되도록 추가
- yml 파일 변동 및 새로 추가해야될 파일이 있습니다! -> 노션에 추가하고 회의 때 한번 더 노티 드릴게요
close: #595

[Feat] 구글 스프레드 시트 연동 로깅

---

src/main/java/org/sopt/makers/internal/community/domain/CommunityPost.java
src/main/java/org/sopt/makers/internal/dto/community/CommunityPostVo.java
src/main/java/org/sopt/makers/internal/dto/community/PostResponse.java
src/main/java/org/sopt/makers/internal/mapper/CommunityResponseMapper.java

[Refactor] 커뮤니티에서 솝티클을 관리할 수 있도록 조회 응답값을 수정
[Refactor] 커뮤니티에서 솝티클을 관리할 수 있도록 조회 응답값을 수정했습니다.
이에 따라 관련 로직인 VO, Mapper 값도 같이 수정되었습니다 :)
close: #599

[Refactor] 커뮤니티에서 솝티클을 관리할 수 있도록 조회 응답값 수정

---

src/main/java/org/sopt/makers/internal/community/service/category/CategoryService.java

커뮤니티 카테고리 목록 조회 수정
- id값 비교 정렬 추가
- closed #601

[Chore] 커뮤니티 카테고리 목록 조회 정렬 수정

---

src/main/java/org/sopt/makers/internal/community/controller/dto/response/ReviewCountResponse.java
src/main/java/org/sopt/makers/internal/community/repository/CommunityPostRepository.java
src/main/java/org/sopt/makers/internal/community/service/ReviewService.java
src/main/java/org/sopt/makers/internal/external/OfficialHomeClient.java
src/main/java/org/sopt/makers/internal/member/controller/dto/response/MemberPropertiesResponse.java
src/main/java/org/sopt/makers/internal/member/mapper/MemberResponseMapper.java
src/main/java/org/sopt/makers/internal/service/MemberService.java

userProperty에 유저별 솝티클 업로드 수 및 활동후기 업로드 수 추가
- userProperty에 유저별 솝티클 업로드 수 추가
- userProperty에 유저별 활동후기 업로드 수 추가
- 활동후기같은 경우, 공홈팀에서 만들어준 api를 통신하여 받아오도록 하였고, 통신에 대한 검증로직도 추가했습니다!
close: #610

[Feat] userProperty에 유저별 솝티클 업로드 수 및 활동후기 업로드 수 추가

---

src/main/java/org/sopt/makers/internal/repository/community/CommunityQueryRepository.java

정렬 순서 생성 날짜 내림차순으로 변경
- orderBy 내용 수정
- closed #616

[Chore]: 정렬 순서 생성 날짜 내림차순으로 변경

---

src/main/java/org/sopt/makers/internal/repository/community/CommunityQueryRepository.java

- Related PR : #618 
정렬 순서 생성 날짜 내림차순으로 변경

RELEASE 2025-05-01 14:52:00

---

src/main/java/org/sopt/makers/internal/external/makers/OfficialHomeClient.java

솝티클 스크랩 이슈 해결
- 수정된 url로 변경
- closed #642

[HotFix] 솝티클 스크랩 이슈 해결

---

src/main/java/org/sopt/makers/internal/community/repository/CommunityQueryRepository.java
src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java

필요없는 메서드를 정리하고, 정렬로직을 최종적으로 수정했습니다.
- 사용하지 않는 메서드 정리
- 정렬로직 최종 수정
close: #653

RELEASE 2025-05-31 1:47:00

---

src/main/java/org/sopt/makers/internal/community/domain/CommunityPost.java
src/main/java/org/sopt/makers/internal/member/domain/Member.java
src/main/java/org/sopt/makers/internal/vote/VoteQueryRepository.java
src/main/java/org/sopt/makers/internal/vote/VoteService.java
src/main/java/org/sopt/makers/internal/vote/domain/Vote.java
src/main/java/org/sopt/makers/internal/vote/domain/VoteOption.java
src/main/java/org/sopt/makers/internal/vote/domain/VoteSelection.java

투표 관련 파일 추가
- Vote, VoteOption, VoteSelection 엔티티 파일을 새로 추가하여 투표 데이터 모델을 구성하였습니다.
- VotesSelection. Vote에 unique설정을 추가하여 원투원이 보장되도록, 중복된 데이터가 저장되지 않도록 설정했습니다.
- 기존 CommunityPost 및 Member 엔티티에 투표 관련 연관관계 및 cascade 설정을 추가하여, 투표 데이터의 무결성과 연쇄 삭제가 가능하도록 하였습니다.
- Repository파일과 Service파일을 추가하였습니다.
[🔗 참고 노션](https://www.notion.so/sopt-makers/SP3-FEBE-21576042aac280d3975df485cd78ed6e) 
- closed: #661

[Feat] 투표 관련 파일 추가

---

src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java

- 유저는 투표한 사항을 수정할 수 없기 때문에, 투표 선택 API에서는 VoteSelection을 추가하고 생성하는 이벤트만 일어나게 됩니다.
- 그래서 PATCH 보다는 POST가 적절하여 해당 내용 수정했습니다 :)
close: #666

[chore] PATCH > POST API로 수정

---

src/main/java/org/sopt/makers/internal/community/dto/response/PostSaveResponse.java
src/main/java/org/sopt/makers/internal/community/mapper/CommunityResponseMapper.java
src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java

[chore] post 응답에 vote 객체 함께 반한하도록 수정
- PostSaveResponse에 Vote 정보를 추가해서 반환할 수 있도록 수정했습니다!
close: #675

[chore] post 응답에 vote 객체 함께 반한하도록 수정

---

src/main/java/org/sopt/makers/internal/vote/service/VoteService.java

- 원본 불변리스트가 아닌 복사한 새로운 가변 리스트를 사용하도록 수정했습니다!
close: #677

[chore] 원본 불변리스트가 아닌 복사한 새로운 가변 리스트를 사용하도록 수정

---

src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
src/main/java/org/sopt/makers/internal/community/dto/response/PostSaveResponse.java
src/main/java/org/sopt/makers/internal/community/mapper/CommunityResponseMapper.java
src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
src/main/java/org/sopt/makers/internal/vote/service/VoteService.java

- 기존 투표 생성 시 투표 초기값을 응답으로 주던 부분을 삭제했습니다.
- 대신 투표 선택 시 현재까지의 투표상황을 클라이언트에게 전달해 투표 상태의 반영속도를 높였습니다 :)
close: #679

[chore] 투표 선택 시 현재 투표상황을 반환하도록 변경

---

src/main/java/org/sopt/makers/internal/community/dto/request/PostUpdateRequest.java
src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java

글 수정시에도 언급 푸시 알람 가도록 수정
- 글 수정시에도 언급 푸시 알람 가도록 수정
- closed: #693

[Fix] 글 수정시에도 언급 푸시 알람 가도록 수정

---

src/main/java/org/sopt/makers/internal/community/dto/request/PostUpdateRequest.java
src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java

* [Fix] 글 수정시에도 언급 푸시 알람 가도록 수정 (#694)

RELEASE 2025-07-07 13:30:00

---

src/main/java/org/sopt/makers/internal/common/auth/jwtFilter/JwtAuthenticationFilter.java
src/main/java/org/sopt/makers/internal/common/auth/jwtFilter/SecurityConfig.java
src/main/java/org/sopt/makers/internal/resolution/controller/AdminController.java
src/main/java/org/sopt/makers/internal/resolution/controller/UserResolutionController.java
src/main/java/org/sopt/makers/internal/resolution/domain/UserResolutionLuckyPick.java
src/main/java/org/sopt/makers/internal/resolution/dto/response/LuckyPickResponse.java
src/main/java/org/sopt/makers/internal/resolution/dto/response/ResolutionResponse.java
src/main/java/org/sopt/makers/internal/resolution/mapper/UserResolutionResponseMapper.java
src/main/java/org/sopt/makers/internal/resolution/repository/UserResolutionLuckyPickRepository.java
src/main/java/org/sopt/makers/internal/resolution/repository/UserResolutionRepository.java
src/main/java/org/sopt/makers/internal/resolution/service/LuckyPickService.java
src/main/java/org/sopt/makers/internal/resolution/service/UserResolutionService.java

- 필드 추가
- 테이블 생성 및 엔티티, 레포지토리 파일 추가
close: #703

[Feat] 타임캡솝 조회 로직 Sp4에 맞게 수정

---

src/main/java/org/sopt/makers/internal/wordchaingame/service/WordChainGameService.java

- 작업 1
- 작업 2
- 작업 3
close: #708

[fix] 단어게임 첫 게임인 경우 룸 조회 안되는 오류 수정

---

src/main/java/org/sopt/makers/internal/community/repository/anonymous/AnonymousCommentProfileRepository.java
src/main/java/org/sopt/makers/internal/community/service/CommunityCommentService.java

- 기존에 익명 프로필의 경우 member = null로 처리되어 조회가 되지 않는 오류가 있었습니다!
- 댓글 ID 기반으로 comment 를 조회하도록 수정하였습니다!
close: #710

[Fix] 댓글 조회 시 commentId 기반으로 조회되도록 수정

---

src/main/java/org/sopt/makers/internal/auth/jwtFilter/JwtAuthenticationFilter.java

jwt 관련 filter 로직 변경
- 인증 중앙화에 따라 access token에 prefix가 붙어야하므로 이를 제거하여 검증하는 로직을 추가했습니다!
close: #721

[Feat] 토큰에서 prefix 제거하는 로직 구현

---

src/main/java/org/sopt/makers/internal/coffeechat/service/CoffeeChatService.java
src/main/java/org/sopt/makers/internal/internal/InternalOpenApiController.java
src/main/java/org/sopt/makers/internal/member/service/MemberService.java
src/main/java/org/sopt/makers/internal/wordchaingame/controller/WordChainGameController.java
src/main/java/org/sopt/makers/internal/wordchaingame/service/WordChainGameService.java

- 작업 1
- 작업 2
- 작업 3
close: #00

[Feat] map 변환 시 duplicate 오류 일어나지 않도록 수정

---

src/main/java/org/sopt/makers/internal/internal/InternalOpenApiController.java
src/main/java/org/sopt/makers/internal/internal/dto/CreateDefaultUserProfileRequest.java
src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
src/main/java/org/sopt/makers/internal/member/domain/Member.java
src/main/java/org/sopt/makers/internal/member/dto/response/MemberProfileResponse.java
src/main/java/org/sopt/makers/internal/member/service/MemberService.java
src/main/java/org/sopt/makers/internal/project/mapper/ProjectResponseMapper.java

- 프로젝트 조회 시 잘못된 유저 아이디 불러오는 문제 해결
- 멤버 검색 시 null 인 경우 분기처리
- closed #740

[Fix] 플그 기본 유저 프로필 생성 api 추가

---

src/main/java/org/sopt/makers/internal/auth/jwtFilter/JwtAuthenticationFilter.java
src/main/java/org/sopt/makers/internal/auth/security/config/SecurityConfig.java
src/main/java/org/sopt/makers/internal/internal/InternalOpenApiController.java

공홈이 사용하는 프로젝트 조회 api 인증 구조 삭제
- 작업 1
- 작업 2
- 작업 3
- closed #742

[Feat] 공홈이 사용하는 프로젝트 조회 api 인증 구조 삭제

---

src/main/java/org/sopt/makers/internal/common/exception/GlobalExceptionHandler.java
src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
src/main/java/org/sopt/makers/internal/internal/InternalOpenApiController.java

프로필 조회 에러 핸들링 및 base url 수정
- 작업 1
- 작업 2
- 작업 3
- closed: #744

[Fix] 프로필 조회 에러 핸들링 및 base url 수정

---

src/main/java/org/sopt/makers/internal/member/service/MemberService.java

멤버 프로필 전체 조회 API에서 플랫폼팀에게 유저 정보 조회 Internal API를 호출하기위해 
올바른 Part 형식으로 요청하도록 수정했습니다!
- 기존 형식
- 수정된 형식
close: #750

[Fix] MemberPart 요청형식 수정

---

src/main/java/org/sopt/makers/internal/common/exception/GlobalExceptionHandler.java
src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
src/main/java/org/sopt/makers/internal/internal/InternalOpenApiController.java
src/main/java/org/sopt/makers/internal/member/service/MemberService.java

인증중앙화 이후 발생한 자잘한 오류들을 해결했습니다 :)

RELEASE 2025-08-31 22:27:00

---

src/main/java/org/sopt/makers/internal/auth/jwt/code/JwkFailure.java
src/main/java/org/sopt/makers/internal/auth/jwt/code/JwtFailure.java
src/main/java/org/sopt/makers/internal/auth/jwt/service/JwkProvider.java
src/main/java/org/sopt/makers/internal/auth/jwt/service/JwtAuthenticationService.java
src/main/java/org/sopt/makers/internal/internal/InternalOpenApiController.java

- 잘못된 import문으로 인해 앱팀 친구추천 api 오류나는 문제 해결
- 플그 이전 세션 남아있을 시 500에러로 재로그인으로 리다이렉션 안되는 문제 해결

RELEASE 2025-09-7 21:27:00 

---

src/main/java/org/sopt/makers/internal/member/service/MemberService.java

cursor 기반이 아닌 offset 기반의 페이지네이션 처리 반영
- #769

[Fix] 멤버 리스트 조회 cursor 파라미터 offset 기반으로 로직 처리

---

src/main/java/org/sopt/makers/internal/member/service/MemberService.java

- 삭제된 멤버탭 정렬 ordering 복구
- #769

[Fix] 멤버 ordering 복구

---

src/main/java/org/sopt/makers/internal/member/service/MemberService.java

[Fix] 삭제된 멤버 정렬 기준 복구

---

src/main/java/org/sopt/makers/internal/external/platform/PlatformService.java
src/main/java/org/sopt/makers/internal/external/platform/SoptActivity.java
src/main/java/org/sopt/makers/internal/member/service/MemberService.java

멤버 리스트 필터링 조회 오류 수정 
- 인증 서버로부터 ```role``` 정보 받아와서 기존 멤버 정보처럼 team 정보 업데이트
- 파트 필터링 오류 수정
- 팀 필터링 오류 수정
- #769

[Fix] 멤버 리스트 필터링 조회 오류 수정

---

src/main/java/org/sopt/makers/internal/coffeechat/repository/CoffeeChatRepository.java
src/main/java/org/sopt/makers/internal/coffeechat/service/CoffeeChatRetriever.java
src/main/java/org/sopt/makers/internal/coffeechat/service/CoffeeChatService.java

커피챗/쪽지 보내기 기능 오류 & 커피챗 오픈 여부 확인 수정
- 커피챗/쪽지 보내기 기능 수신자 정보 senderId 로 처리되는 부분 수정
- 커피챗 오픈 여부 isCoffeeChatActivate 필드 함께 확인하도록 수정

[Fix] 커피챗/쪽지 보내기 기능 오류 & 커피챗 오픈 여부 확인 수정
