src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChat.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatCreator.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java

SP1 커피챗 고도화에서 추가된 필드를 바탕으로 정보를 삭제하는 API를 추가합니다.
- 코드리뷰의 편의를 위해 https://github.com/sopt-makers/sopt-playground-backend/pull/494 와 분리하여 PR 생성합니다.
- 커피챗 정보 삭제 API
- CoffeeChat -> Member `Cascade.REMOVE` 제약 조건 제거
related issue: #482

[Feat] 커피챗 정보 삭제 API

---

src/main/java/org/sopt/makers/internal/member/domain/coffeechat/Career.java
src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChatSection.java
src/main/java/org/sopt/makers/internal/member/domain/coffeechat/MeetingType.java

- 개발 편의성을 위해 FE와 요청-응답에 주고받는 enum title 명을 통일합니다.
- [관련 스레드](https://sopt-makers.slack.com/archives/C04SPCUJ2DQ/p1729863225919029?thread_ts=1729863174.103309&cid=C04SPCUJ2DQ)
- Career
- CoffeeChatSection
- MeetingType
위 enum명을 FE와 통일합니다.
related issue #482

[Chore] enum title명 FE와 sync

---

src/main/java/org/sopt/makers/internal/dto/member/MemberProfileResponse.java
src/main/java/org/sopt/makers/internal/mapper/MemberMapper.java
src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatRetriever.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java

멤버 프로필 조회 시, isCoffeeChatActivate 필드는 신규 생성된 coffee_chat 테이블을 바라보도록 수정합니다. 
- 커피챗 조회 시, 기존 로직 활용 (단, NotFoundDBException이 발생할 수 있으므로 try-catch로 예외처리 후 항상 false를 반환하도록 함)
- 기존 프로필 response에서 coffee_chat_bio는 제거
- 멤버 프로필 mapper 로직 수정: Controller 단에서 coffeeChat 정보를 가져오고 mapper에서 매핑하도록 함
related issue: #498

[Chore] member profile response

---

src/main/java/org/sopt/makers/internal/community/domain/CommunityPostLike.java

created_at이 null로 업데이트 되는 현상을 막기 위해 엔티티 연관관계 매핑에서 `updatable=false` 속성을 추가합니다. (default는 true)
- 엔티티 연관관계 속성 추가
- createdAt 대신 updatedAt을 기준으로 정렬하는 것은 일단 보류 (문제 재발 시 긴급 조치로 updatedAt 내림차순 정렬로 수정하겠습니다)
close: #507

[Fix] 커뮤니티 게시글 좋아요 연관관계 updatable 속성 지정

---

src/main/java/org/sopt/makers/internal/external/gabia/GabiaService.java

커피챗 문자 발송 시 장문의 문자도 발신이 가능하도록 합니다.
- 메시지 본문 길이에 따라 호출하는 가비아 API의 endpoint를 다르게 지정합니다. (비용 한도를 효율적으로 사용하기 위함)
- API 는 정상적으로 처리되는 것을 확인했습니다. 
- dev 서버에서 테스트했을 때 문자가 정상적으로 수신되는지 확인해야 qa가 완료됩니다.
close: #518

[Feat] LMS endpoint 추가

---

src/main/java/org/sopt/makers/internal/dto/member/MemberProfileUpdateRequest.java
src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/request/CoffeeChatDetailsRequest.java
src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChat.java

커피챗 테이블의 meetingType을 not null 필드로 변경하고, production/dev 테이블의 스키마 변경 및 더미 데이터 추가를 반영합니다. 
related issue: #489

chore: CoffeeChat meetingType not null로 제한

---

.gitignore
src/main/java/org/sopt/makers/internal/community/repository/AnonymousProfileImageRepository.java
src/main/java/org/sopt/makers/internal/community/service/AnonymousProfileImageService.java

Related to: #535
익명 댓글을 작성할 때 메이커스 로고가 선택되는 경우를 방지했습니다.
이미지 목록 Map에 초기화 할 때 id가 6인 이미지는 제외했습니다.
- 작업 1
- 작업 2
- 작업 3
close: #535

[Fix]: 메이커스 이미지 방지

---

src/main/java/org/sopt/makers/internal/dto/member/MemberProfileSpecificResponse.java
src/main/java/org/sopt/makers/internal/mapper/MemberMapper.java
src/main/java/org/sopt/makers/internal/member/controller/MemberController.java

멤버 프로필 쪽 coffee chat migration 시 미적용된 부분이 있어 마저 반영합니다. 
- 작업 1
- 작업 2
- 작업 3
close: #00

[Fix] 멤버 coffee chat 관련 필드 반영

---

src/main/java/org/sopt/makers/internal/dto/member/MemberProfileSpecificResponse.java
src/main/java/org/sopt/makers/internal/mapper/MemberMapper.java
src/main/java/org/sopt/makers/internal/member/controller/MemberController.java

반영이 안 된 부분이 있어 다시 올립니다!
- https://github.com/sopt-makers/sopt-playground-backend/pull/540 PR에서 checkPhoneBlind()의 변경사항을 추가합니다. 해당 함수에서 새로운 response 객체를 반환하는 로직에 의해 의도한 결과가 반환되지 않는 문제를 해결했습니다

[Fix] isCoffeeChatActivate param 추가

---

src/main/java/org/sopt/makers/internal/community/repository/CommunityPostRepositoryCustom.java
src/main/java/org/sopt/makers/internal/community/repository/CommunityPostRepositoryCustomImpl.java
src/main/java/org/sopt/makers/internal/community/service/CommunityPostService.java
src/main/java/org/sopt/makers/internal/controller/InternalOpenApiController.java
src/main/java/org/sopt/makers/internal/dto/community/InternalCommunityPost.java
src/main/java/org/sopt/makers/internal/dto/community/PostCategoryDao.java
src/main/java/org/sopt/makers/internal/dto/internal/InternalMemberProjectResponse.java
src/main/java/org/sopt/makers/internal/mapper/CommunityResponseMapper.java
src/main/java/org/sopt/makers/internal/mapper/ProjectResponseMapper.java
src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/response/InternalCoffeeChatMemberResponse.java
src/main/java/org/sopt/makers/internal/member/controller/dto/response/InternalMemberInfoResponse.java
src/main/java/org/sopt/makers/internal/member/mapper/coffeechat/CoffeeChatResponseMapper.java
src/main/java/org/sopt/makers/internal/member/repository/coffeechat/dto/InternalCoffeeChatMemberDto.java
src/main/java/org/sopt/makers/internal/member/service/MemberRetriever.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
src/main/java/org/sopt/makers/internal/repository/MemberProfileQueryRepository.java
src/main/java/org/sopt/makers/internal/repository/ProjectQueryRepository.java
src/main/java/org/sopt/makers/internal/repository/community/CommunityPostRepository.java
src/main/java/org/sopt/makers/internal/repository/community/CommunityQueryRepository.java
src/main/java/org/sopt/makers/internal/service/MemberService.java
src/main/java/org/sopt/makers/internal/service/ProjectService.java

앱팀에서 요청한 internal api를 구현했습니다.
- [관련 스레드](https://sopt-makers.slack.com/archives/C042T81PW80/p1730802286241589)
작업하면서 느낀 건데, 타 팀의 internal api 요청에 의해 중복 코드를 남발하는 구조인 것 같습니다.
최대한 중복 로직을 줄이고, 같은 엔티티에 대해 여러 개의 mapper, dto를 만들지 않도록 구조 리팩토링이 우선일 것 같고 타 팀의 요청자와 작업자 간의 요구사항 싱크를 위해 체계화된 워크플로우가 있으면 좋겠다는 생각이 듭니다 
코드는 좀 급하게 짜느라.. 맘껏 리뷰해주십쇼 ..!
- category별 최근 커뮤니티 게시글 조회 API
- 커피챗 활성 유저 리스트 조회 API
- 회원 id로 프로젝트 정보 조회 API
close: #548

[Feat] internal api for app

---

src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatRepositoryCustomImpl.java

회의 때 논의된 요청사항에 따라 전체 커피챗 리스트의 최신순 정렬 기능을 추가합니다.
- 작업 1
- 작업 2
- 작업 3
close: #557

[Feat] coffee chat 최신순 정렬 추가

---

src/main/java/org/sopt/makers/internal/external/MessageSenderFactory.java
src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/request/CoffeeChatRequest.java
src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java

쪽지 보내기 API에서 커피챗 카테고리에 대해서도 메일 발송이 가능하도록 sender 구현체 판단 조건을 수정합니다. 
- request validation 추가
- sender return 조건 수정
close: #569

feat: 커피챗 메일 발송 가능하도록 수정

---

.github/workflows/cd-to-dev.yml
.github/workflows/cd-to-prod.yml
docker-compose.yml
scripts/deploy.sh
scripts/nginx_reload.sh

- 작업 1
- 작업 2
- 작업 3
close: #00

chore: update directory name

---

src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/request/CoffeeChatDetailsRequest.java
src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChat.java

Related to: #572
커피챗 자기소개 필드 옵셔널로 변경
dev, prod db에서 해당 필드 optional로 바꿔줘야할 것 같습니다!
- 커피챗 자기소개 필드 옵셔널로 변경
close: #572

[Fix]: 커피챗 자기소개 필드 옵셔널로 변경

---

build.gradle
src/main/java/org/sopt/makers/internal/common/Constant.java
src/main/java/org/sopt/makers/internal/community/repository/CommunityPostLikeRepository.java
src/main/java/org/sopt/makers/internal/community/repository/CommunityPostRepository.java
src/main/java/org/sopt/makers/internal/config/cache/CacheConfig.java
src/main/java/org/sopt/makers/internal/config/cache/CacheConstant.java
src/main/java/org/sopt/makers/internal/config/cache/CacheType.java
src/main/java/org/sopt/makers/internal/dto/amplitude/AmplitudeEventResponse.java
src/main/java/org/sopt/makers/internal/dto/amplitude/AmplitudeUserResponse.java
src/main/java/org/sopt/makers/internal/external/amplitude/AmplitudeClient.java
src/main/java/org/sopt/makers/internal/external/amplitude/AmplitudeService.java
src/main/java/org/sopt/makers/internal/external/amplitude/EventData.java
src/main/java/org/sopt/makers/internal/report/controller/SoptReportStatsController.java
src/main/java/org/sopt/makers/internal/report/domain/PlaygroundType.java
src/main/java/org/sopt/makers/internal/report/dto/PlayGroundTypeStatsDto.java
src/main/java/org/sopt/makers/internal/report/dto/response/MySoptReportStatsResponse.java
src/main/java/org/sopt/makers/internal/report/service/SoptReportStatsService.java
src/main/java/org/sopt/makers/internal/repository/WordChainGameQueryRepository.java
src/main/java/org/sopt/makers/internal/repository/WordRepository.java
src/main/java/org/sopt/makers/internal/repository/community/CommunityCommentRepository.java

SP3 마이 솝트 리포트에서 `마이 플그` 파트에 해당하는 유저 개인화 데이터를 조회하는 API를 구현합니다.
[API 명세서
](https://www.notion.so/sopt-makers/API-6fa331660d334ad4940fb3574b8f5e2e?pvs=4)
- Amplitude Dashboard API를 호출하여 playground user id -> amplitude user id 조회 -> 해당 id로 유저 이벤트 프로퍼티 목록을 조회합니다. 
- 리포트에 포함되는 데이터를 서버 내부에서 전처리하여 내려주기 위함입니다. (웹 페이지 상에서 호출하면 CORS가 발생하고, 응답 데이터가 커서 가공이 필요)
- 호출 시마다 변화되는 동적 데이터가 아니라, 2024년도 기준의 고정 데이터이므로 로컬 캐싱을 적용하여 DB 호출 수를 최소화하고 성능을 향상시키고자 했습니다.
- amplitude api를 호출하는 빈도 역시 최소화하기 위해 유저마다 일주일의 ttl을 갖도록 했습니다. 
+) 추후 크루 API 개발이 완료되면 작업이 필요한데, FE분들 작업을 위해 해당 PR 배포 후에 별도 PR로 올리겠습니다!
close: #581

[Feat] 마이 솝트 리포트 마이 플그 파트 데이터 조회 API

---

src/main/java/org/sopt/makers/internal/external/MakersCrewClient.java
src/main/java/org/sopt/makers/internal/external/amplitude/AmplitudeService.java
src/main/java/org/sopt/makers/internal/external/amplitude/EventData.java
src/main/java/org/sopt/makers/internal/report/dto/CrewFastestJoinedGroupResponse.java
src/main/java/org/sopt/makers/internal/report/service/SoptReportStatsService.java
src/test/resources/application.yml

SP3 마이 솝트 리포트 공통 데이터 / 마이 데이터 조회 API에서 크루 데이터를 조회하는 로직을 추가합니다.
- 크루 외부 API 통신 추가
- 플그 유저 단위 가장 빠르게 신청한 모임 타이틀 리스트를 조회하는 부분 
- 크루 앰플리튜드 데이터 조회 로직 추가
- 모임 탭 조회 카운트를 Crew Amplitude ApiKey와  SecretKey로 조회하도록 추가
close: #581

[Feat] 마이 솝트 리포트 크루 데이터 추가

---

src/main/java/org/sopt/makers/internal/resolution/controller/UserResolutionController.java
src/main/java/org/sopt/makers/internal/resolution/service/UserResolutionService.java

- 36기 타임캡솝의 조회 관련 로직을 수정하고, 삭제하는 로직을 추가했습니다.
close: #593

[Chore] 타임캡솝 조회 및 삭제 기능 수정 및 추가

---

src/main/java/org/sopt/makers/internal/resolution/controller/UserResolutionController.java
src/main/java/org/sopt/makers/internal/resolution/domain/ResolutionTag.java
src/main/java/org/sopt/makers/internal/resolution/domain/UserResolution.java
src/main/java/org/sopt/makers/internal/resolution/dto/request/ResolutionSaveRequest.java
src/main/java/org/sopt/makers/internal/resolution/dto/response/ResolutionResponse.java
src/main/java/org/sopt/makers/internal/resolution/mapper/UserResolutionResponseMapper.java
src/main/java/org/sopt/makers/internal/resolution/service/UserResolutionService.java

36기 새롭게 바뀐 타임캡솝 태그값들을 수정하였습니다.
- 태그값들 새롭게 수정된 값으로 변경
- 태그값들 인덱스가 아닌 값이 디비에 저장되도록 변경
- 타임캡솝 메시지 작성 성공 시 response 형식 수정
- UserResolutionService의 getResoution(조회하는 함수)에서 한 줄의 코드 수정이 있었습니다. 같은 함수 내에서 작업이 충돌될 것 같아 이부분 말씀드립니다!
- 두 명 모두 수정작업 완료한 이후 resolution->timecapsop으로 네이밍 변경하는 작업하면 좋을 것 같습니다!
close: #593

[Chore] 타임캡솝 태그 유형 수정

---

src/main/java/org/sopt/makers/internal/community/domain/CommunityPost.java
src/main/java/org/sopt/makers/internal/dto/community/CommunityPostVo.java
src/main/java/org/sopt/makers/internal/dto/community/PostResponse.java
src/main/java/org/sopt/makers/internal/mapper/CommunityResponseMapper.java

클라측 요청 사항에 따라
/api/v1/community/posts 에서  isSopticle 필드를 사용하지 않고도 categoryId로 솝티클 여부 판단이 가능해서 해당 값을 지우도록 수정했습니다!
- VO 수정
- PostReponse 수정
- Mapper 수정
- CommunityPost 수정
- DB 반영
close: #603

[Refac] 불필요한 Column 어노테이션 삭제

---

src/main/java/org/sopt/makers/internal/community/service/SopticleService.java
src/main/java/org/sopt/makers/internal/domain/Part.java

공홈 API 요청 시 part 값 변환 로직 삭제
- 공홈 API 요청 시 part 값 변환 로직 삭제
- closed #607

[Fix] 공홈 API 요청 시 part 값 변환 로직 삭제

---

src/main/java/org/sopt/makers/internal/community/dto/response/ReviewCountResponse.java

알림서버의 /api/v1/members/property API에서 외부 API 응답 파싱 오류가 발생했습니다.
ReviewCountResponse.ReviewDto.subject 필드 타입이 String으로 선언되어 있으나, 
실제 응답은 Array 형태(List)로 반환되고 있어 이로 인해 400 Bad Request 발생 중인 상황입니다.
- 필드 형식 변경
close: #623

[Fix]: Subject 필드를 리스트 형태로 받아오도록 수정

---

src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
src/main/java/org/sopt/makers/internal/community/dto/MemberVo.java
src/main/java/org/sopt/makers/internal/community/dto/response/PopularPostResponse.java
src/main/java/org/sopt/makers/internal/community/mapper/CommunityResponseMapper.java
src/main/java/org/sopt/makers/internal/community/repository/CommunityQueryRepository.java
src/main/java/org/sopt/makers/internal/community/repository/post/CommunityPostRepository.java
src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java

인기글 3개 조회 API 구현
- 인기글 3개 조회 API 구현
- CommunityMapper 내 Member -> MemberVo 변환 메소드를 MemberVo DTO 안으로 위치 변경 및 기존 정렬 로직 올바르게 수정
- 이유1: controller에서 reponse로 변환하는 메소드로 사용하는게 아닌 상황입니다
- 이유2: controller가 아닌 타 파일 내에서 사용 시 Mapper 클래스 선언 없이 사용하고 싶었습니다
- 이유3: MemberVo DTO 변환 책임을 DTO 파일에게 주고 싶습니다
- 카테고리 id를 name으로 변경하는 로직을 다른 메소드에 있던 query문 활용해서 queryRepository에 빼두기
- 이유1: Enum으로 카테고리가 선언되어 있지 않아 선언하고 변환할까 하다가, enum으로 관리할 시 parent 카테고리 포함 너무 많아지게 될 것 같아 복잡할 것 같았습니다
- 이유2: 이후 커뮤니티 카테고리 수정 작업 시 많은 카테고리를 코드로 유지보수하기 까다로울 것 같아, db에서만 관리하자 싶어 query문 활용했습니다!
- closed #627

[Feat] 인기글 3개 조회 API 구현

---

src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
src/main/java/org/sopt/makers/internal/community/dto/MemberVo.java
src/main/java/org/sopt/makers/internal/community/dto/response/PopularPostResponse.java
src/main/java/org/sopt/makers/internal/community/repository/CommunityQueryRepository.java
src/main/java/org/sopt/makers/internal/community/repository/post/CommunityPostRepository.java
src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
src/main/java/org/sopt/makers/internal/member/domain/Member.java
src/main/java/org/sopt/makers/internal/member/dto/response/MemberNameAndProfileImageResponse.java

인기글 조회 API 요구사항 변경 및 조회 속도 향상
- Response 필드 중 Member에 대해 필요한 id, name, image만 보내주는 reponse 파일을 새로 만들었습니다. 기존 구현 방식 이유는 MemberVo를 재사용하고자 했으나, 필요없는 정보를 조회하는 쿼리문이 너무 길어 필요한 정보만 조회해 보내주는 것이 맞다고 생각해 새로 `MemberNameAndProfileImageResponse` 파일을 추가하였습니다. (해당 변경사항 내용 FE에게 전달 완료)
- 인기글 조회 시 기존 구현은 jpa 메소드를 사용했으나, SQL 쿼리 실행문을 보며 최적화하던 중 성능 향상을 위해 fetch join을 사용하도록 `communityQueryRepository에 메소드를 추가`하고 적용하였습니다.
- Member Entity의 oneToMany 관계인 activities 필드에 fetchtype을 lazy로 수정하여 조회가 필요한 경우에만 외래키를 사용해 조회되도록 수정하였습니다. (플그 api 중 멤버 id, name 등 적은 정보만 가져오는 api가 많은 것에 비해 항상 다른 테이블과 join하여 activities정보까지 가져오는 경우가 불필요하다고 생각했습니다)
- 슬랙 내 FE, PM 요구사항에 맞춰 title이 빈 값이 올 경우 content를 보내주는 것으로 수정했습니다!
- closed #634

[Refac] 인기글 조회 API 요구사항 변경 및 조회 속도 향상

---

src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
src/main/java/org/sopt/makers/internal/community/dto/response/PopularPostResponse.java
src/main/java/org/sopt/makers/internal/community/mapper/CommunityResponseMapper.java
src/main/java/org/sopt/makers/internal/community/repository/CommunityQueryRepository.java
src/main/java/org/sopt/makers/internal/community/repository/anonymous/AnonymousPostProfileRepository.java
src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java

인기글 글 조회 시 익명글은 익명 프로필 처리하도록 수정
- 인기글 글 조회 시 익명글은 익명 프로필 조회해서 적용되도록 쿼리문 추가하였습니다.
- 기존 커뮤니티 글 상세/전체 조회 시 익명글의 익명 프로필 조회하던 로직이 memberId와 communityPostId를 함께 조건으로 조회했지만, DB 구조상 communityPostId는 고유한 값이므로 단독 조회로 충분하다고 판단하여 불필요한 조건을 제거하였습니다.
- 인기글 Response 변환 로직 Mapper로 이동하였습니다.
- 사용하지 않는 메서드 2개를 제거하였습니다.
- closed #640

[Fix] 인기글 글 조회 시 익명글은 익명 프로필 처리하도록 수정

---

src/main/java/org/sopt/makers/internal/community/controller/CommunityCategoryController.java
src/main/java/org/sopt/makers/internal/community/domain/category/Category.java
src/main/java/org/sopt/makers/internal/community/dto/response/CommunityCategoryResponse.java
src/main/java/org/sopt/makers/internal/community/service/category/CategoryService.java
src/test/java/org/sopt/makers/internal/service/community/category/CategoryServiceUnitTest.java

[Refactor] 카테고리 반환해 주는 API 정렬 순서 변경
- 전체 카테고리 조회 API의 코드에도 displayOrder에 따른 정렬 이후 데이터를 응답하도록 수정했습니다!
close: #650

[Refactor] 카테고리 반환해 주는 API 정렬 순서 변경

---

src/main/java/org/sopt/makers/internal/common/util/MentionCleaner.java
src/main/java/org/sopt/makers/internal/community/dto/request/CommentSaveRequest.java
src/main/java/org/sopt/makers/internal/community/dto/request/MentionRequest.java
src/main/java/org/sopt/makers/internal/community/dto/request/PostSaveRequest.java
src/main/java/org/sopt/makers/internal/community/service/CommunityCommentService.java
src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
src/main/java/org/sopt/makers/internal/external/pushNotification/PushNotificationService.java
src/main/java/org/sopt/makers/internal/mention/MentionRequest.java
src/main/java/org/sopt/makers/internal/scheduler/PushNotificationScheduler.java

게시물 및 댓글에서 언급 푸시 알람 연동
- Sp3 관련: 
- 커뮤니티 글, 댓글 생성 시 mentionRequest 필드를 추가하였습니다.
- 커뮤니티 글, 댓글에서 언급 시 푸시 알람 전송 되도록 연결하였습니다.
- 언급 알람 전송 시 메시지에는 @임주민[221] 형태가 보이지 않도록 [221]을 제거해주는 MentionCleaner 유틸리티 클래스를 추가하였습니다. 
- 기존에 존재하던 알람로직인 '자신의 게시물에 새로운 댓글 달렸을 때' 알람 전송 되는 메시지 형태를 새로운 요구사항에 따라 변경하였습니다.
- closed #682

[Feat] 언급 푸시 알람 연동

---

src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
src/main/java/org/sopt/makers/internal/community/dto/response/RecentPostResponse.java
src/main/java/org/sopt/makers/internal/community/mapper/CommunityResponseMapper.java
src/main/java/org/sopt/makers/internal/community/repository/post/CommunityPostRepository.java
src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
src/test/java/org/sopt/makers/internal/community/service/post/CommunityPostServiceTest.java

[Refactor] 홈 질문 최근글 불러오기 api 모든 카테고리 최근글 불러오기로 수정
- 홈 질문 최근글 불러오기 api를 솝티클 카테고리를 제외한 모든 카테고리의 최근글을 불러올 수 있도록 변경했습니다 :)
- 최신글을 조회하기 전, 해당하는 카테고리를 미리 조회하여 N+1 문제를 방지하고자 했습니다!
- 테스트 코드를 통해 해당 기능 검증을 완료했습니다.
close: #681

[Refactor] 홈 질문 최근글 불러오기 api 모든 카테고리 최근글 불러오기로 수정

---

src/main/java/org/sopt/makers/internal/community/mapper/CommunityResponseMapper.java
src/main/java/org/sopt/makers/internal/community/service/category/CategoryRetriever.java
src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
src/main/java/org/sopt/makers/internal/member/repository/MemberProfileQueryRepository.java
src/main/java/org/sopt/makers/internal/member/service/MemberService.java
src/test/java/org/sopt/makers/internal/community/service/post/CommunityPostServiceTest.java
src/test/java/org/sopt/makers/internal/service/community/category/CategoryServiceUnitTest.java

기존 멤버 검색 api 리팩토링(개수 리밋, 보여주는 순서, 코드 최적화)
- 기존 멤버 검색 api 리팩토링(개수 리밋, 보여주는 순서, 코드 최적화)
기존 코드는 이름(name)을 기준으로 포함되는 모든 멤버를 조회하는 단순한 로직이었습니다. 이번에는 하나의 API 엔드포인트에서 초기 랜덤 유저 조회와 이름 기반 검색을 모두 처리하고, 정렬 순서와 개수 제한까지 적용하는 방식으로 리팩토링하였습니다.
- 시나리오는 아래와 같습니다.
시나리오 1 (초기 진입): 검색어(name)가 없거나 @일 경우, 랜덤 유저 30명을 반환합니다.
시나리오 2 (검색 시): 검색어가 있을 경우, 해당 검색어가 이름에 포함된 유저를 최신 활동 기수 순서로 정렬하여 반환합니다.
- Respository는 QueryDSL을 활용하여 복잡한 동적쿼리에 대한 안정성을 고려했습니다.
close: #685

[Refactor] 기존 멤버 검색 api 리팩토링(개수 리밋, 보여주는 순서, 코드 최적화)

---

src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java

- 자식 카테고리를 가진 '홍보'(ID: 4L)와 '파트Talk'(ID: 2L) 카테고리에서 최신 게시글을 조회할 때, 해당 게시글이 자식 카테고리에 속해 있을 경우 categoryName이 정상적으로 반환되지 않는 문제가 있었습니다.
- 원인은 getInternalLatestPosts 메서드 에서 게시글(post)에 직접 저장된 categoryId를 사용하여 categoryNameMap에서 카테고리 이름을 조회했지만 categoryNameMap에는 최상위 카테고리 정보만 담겨 있어, 게시글이 하위 카테고리에 속한 경우 해당 ID를 찾지 못해 빈 문자열("")이 반환되었습니다!
- 이 문제를 해결하기 위해, 게시글 자체의 categoryId가 아닌, 반복문에서 사용 중인 **최상위 카테고리 ID (categoryId)**를 사용해 categoryNameMap에서 이름을 조회하도록 수정했습니다!
close: #700

[Fix] 상위 카테고리 조회 문제 해결

---

src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
src/main/java/org/sopt/makers/internal/community/dto/response/PostResponse.java
src/main/java/org/sopt/makers/internal/community/mapper/CommunityResponseMapper.java
src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
src/main/java/org/sopt/makers/internal/external/makers/CrewMeeting.java
src/main/java/org/sopt/makers/internal/external/makers/CrewMeetingListResponse.java
src/main/java/org/sopt/makers/internal/external/makers/CrewPost.java
src/main/java/org/sopt/makers/internal/external/makers/CrewPostListResponse.java
src/main/java/org/sopt/makers/internal/external/makers/MakersCrewClient.java

[Feat] 카테고리에 모임글 불러오기 API 연결
- 크루팀의 API를 연결해 모임 카테고리 클릭 시, 크루 팀 모임 피드 전체 조회 API 를 호출하여 피드를 불러오도록 구현했습니다..!
close: #719

[Feat] 카테고리에 모임글 불러오기 API 연결

---

src/main/java/org/sopt/makers/internal/coffeechat/service/CoffeeChatService.java
src/main/java/org/sopt/makers/internal/member/mapper/MemberMapper.java

커피챗 검색 API의 필터링 오류를 수정하고, 
프로필 수정 API의 응답 데이터에서 활동 정보(activities)가 누락되는 문제를 해결했습니다.
- 커피챗 검색 API 필터링 로직 수정
기존에는 검색 조건을 분리하여 처리 후 병합하는 과정에서 '파트' 필터가 우회되거나 동일 데이터가 중복으로 포함될 수 있는 문제가 있었습니다.
필터를 순차적으로 적용하도록 로직을 변경하여 문제를 해결했습니다 :)
- 프로필 수정(PUT) API 응답 데이터 누락 문제 해결
프로필 수정 후 응답 객체를 생성할 때, MemberMapper에서 활동 정보 필드(soptActivities -> activities)가 명시적으로 매핑되지 않아 null로 반환되었습니다. 응답 데이터에 활동 정보가 정상적으로 포함되도록 수정했습니다!
close: #748

[Fix] 커피챗 중복정보 응답 수정 및 memberProfile의 activities 정보 누락 수정

---

src/main/java/org/sopt/makers/internal/member/dto/response/MemberProfileSpecificResponse.java

[Fix] isBlinder 여부와 상관없이 isMine이 true면 phoneNumber를 보여주도록 수정했어요!
- 기존에는 isPhoneBlind가 true라면 phone정보도 null로 보내주는 오류가 있었습니다!
- 이번 작업에서는 isMine이 true인 경우 isPhoneBlind여부와 상관없이 phoneNumber를 정상적으로 보내주도록 수정했습니다!
close: #756

[Fix] isBlinder 여부와 상관없이 isMine이 true면 phoneNumber를 보여주도록 수정

---

src/main/java/org/sopt/makers/internal/external/platform/GetPlatformUserBatchRequest.java
src/main/java/org/sopt/makers/internal/external/platform/PlatformClient.java
src/main/java/org/sopt/makers/internal/external/platform/PlatformService.java
src/main/java/org/sopt/makers/internal/member/repository/MemberProfileQueryRepository.java
src/main/java/org/sopt/makers/internal/member/service/MemberService.java

멤버 필터링 조회 로직 수정
1. 플그 서버에서 필터링이 가능한 조건에 해당하는 모든 userIds 조회
2. 모든 userIds 기반으로 인증서버 유저 정보 요청
3. 인증서버에서 받아온 멤버 목록에서 기수 및 팀 필터링 진행
4. 최종적으로 조건에 해당하는 모든 멤버 반환
5. 서버 내에서 임의의 Pagination 적용 (Cursor 기반)
⇒ 정상적인 방법의 Pagination 처리는 아니지만, 현재 구조에서는 최선의 방안
1. 최신 기수
2. 프로필 정보량
3. 이름 ㄱㄴㄷ 순
* 인증 서버에서 정보가 없는 ID 조회 시도 시, 에러 반환 대신 warning log 만 남기도록 처리
- #769

[Fix] 멤버 필터링 조회 및 페이지네이션 처리 로직 수정

---

src/main/java/org/sopt/makers/internal/external/platform/PlatformService.java
src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
src/main/java/org/sopt/makers/internal/member/service/MemberService.java

- 멤버 수정 관련 오류 수정
- 페이지네이션 필드 cursor → offset 
- 멤버 수정 오류
- https://sopt-makers.slack.com/archives/C042T81PW80/p1758821241792529
- 페이지네이션 필드값 수정
- https://sopt-makers.slack.com/archives/C042T81PW80/p1758259666826879
- #769

[Fix] 37기 QA 멤버 이슈 수정
